[project]
name = "example-app"
version = "0.1.0"
description = "A Flet example application."
requires-python = ">=3.10"
authors = [
    { name = "TheEthicalBoy", email = "the.ethical@boy.com" }
]

dependencies = [
    "flet==0.81.1.dev7731",
    "flet-webview==0.81.1.dev7731"
]

# Docs: https://flet.dev/docs/publish
[tool.flet]
product = "Example App"
build_number = 1

[tool.flet.app]
path = "src"