[project]
name = "example-app"
version = "0.1.0"
description = "A Flet example application."
requires-python = ">=3.10"
authors = [
    { name = "TheEthicalBoy", email = "the.ethical@boy.com" }
]

dependencies = [
  "flet",
  "selenium"
]

# Docs: https://flet.dev/docs/publish
[tool.flet]
org = "com.mycompany"
product = "flet-build-example"
company = "TheEthicalBoy"
copyright = "Copyright (C) 2025 by TheEthicalBoy"

[tool.flet.app]
path = "src"
