name: All Builds (Linux, macOS, Windows, IPA, APK, AAB, Web)

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  schedule:
    - cron: "0 12 * * *"   # runs every day at 12:00 noon UTC

env:
  # https://flet.dev/docs/publish#versioning
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  UV_PYTHON: 3.12
  UV_PRERELEASE: "allow"
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python dependencies
        run: |
          uv venv
          uv pip install "flet[cli] >=0.70.0.dev0"
          
      - name: Install Linux dependencies
        shell: bash
        run: |
          sudo apt update --allow-releaseinfo-change
          sudo apt-get install -y --no-install-recommends \
            clang \
            ninja-build \
            libgtk-3-dev \
            libasound2-dev \
            libmpv-dev \
            mpv \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-bad1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            gstreamer1.0-tools \
            gstreamer1.0-x \
            gstreamer1.0-alsa \
            gstreamer1.0-gl \
            gstreamer1.0-gtk3 \
            gstreamer1.0-qt5 \
            gstreamer1.0-pulseaudio
      
          sudo apt-get clean

      - name: Flet Build Linux
        run: |
          uv run flet build linux --yes --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: linux-build-artifact
          path: build/linux
          if-no-files-found: warn
          overwrite: false

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv venv
          uv pip install "flet[cli] >=0.70.0.dev0"

      - name: Flet Build macOS
        run: |
          uv run flet build macos --yes --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: macos-build-artifact
          path: build/macos
          if-no-files-found: warn
          overwrite: false

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        
      - name: Install dependencies
        shell: bash
        run: |
          uv venv
          uv pip install "flet[cli] >=0.70.0.dev0"

      - name: Flet Build Windows
        shell: bash
        run: |
          uv run flet build windows --yes --verbose --no-rich-output --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: windows-build-artifact
          path: build/windows
          if-no-files-found: warn
          overwrite: false

  build-aab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv venv
          uv pip install "flet[cli] >=0.70.0.dev0"

      - name: Flet Build AAB
        run: |
          uv run flet build aab --yes --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: aab-build-artifact
          path: build/aab
          if-no-files-found: warn
          overwrite: false

  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv venv
          uv pip install "flet[cli] >=0.70.0.dev0"

      - name: Flet Build APK
        run: |
          uv run flet build apk --yes --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: apk-build-artifact
          path: build/apk
          if-no-files-found: warn
          overwrite: false

  build-ipa:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv venv
          uv pip install "flet[cli] >=0.70.0.dev0"

      - name: Flet Build IPA
        run: |
          uv run flet build ipa --yes --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION 

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: ipa-build-artifact
          path: build/ipa
          if-no-files-found: warn
          overwrite: false
  
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv venv
          uv pip install "flet[cli] >=0.70.0.dev0"

      - name: Flet Build Web
        run: |
          uv run flet build web --yes --verbose

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: web-build-artifact
          path: build/web
          if-no-files-found: warn
          overwrite: false
