name: Linux Build 

on:
  # Runs on push to any of the below branches
  push:
    branches: 
      - apk

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python 3.12.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Patch for linux build
      run: |
        flutter doctor
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
        flutter doctor
    - name: Flet Build Linux
      run: |
        echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}, USER: ${GITHUB_REPOSITORY%/*}, PROJECT_BASE_URL: ${GITHUB_REPOSITORY#*/}"
        
        flutter config --no-analytics # disable flutter analytics
        flutter doctor
        
        flet build linux --help       # Display help for the Flet build command
        flet build linux --verbose    # adapt the command to your needs - https://flet.dev/docs/publish 

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4.3.4  # https://github.com/marketplace/actions/upload-a-build-artifact
      with:
        name: linux-build-artifact  # the name of the artifact
        path: build/linux  # location of Flet build output
        if-no-files-found: error  # Fail the action with an error message if no files are found
        overwrite: false  # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.


